# Generated by Django 5.0 on 2024-02-17 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exp',
            old_name='owner',
            new_name='user',
        ),
    ]
