# Generated by Django 5.0 on 2024-02-17 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTracker', '0002_rename_owner_exp_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exp',
            old_name='user',
            new_name='owner',
        ),
    ]
